-- Módulo: constantes visuais e da tabela (fonte única para CEF.CONST)
-- Deve carregar antes de UILayout/UIEngine/UI.

ClassicEraFinder = ClassicEraFinder or {}
local CEF = ClassicEraFinder

local ROW_HEIGHT = 22
local MAX_STORED = 250
local ENTRY_MAX_LISTING_AGE_SEC = 3600
local MAX_ROW_FRAMES_POOL = 42
local TABLE_PAD = 10
local COL_GAP = 6
local INSTANCE_LEVELS_TO_MSG_GAP = 8
local ROW_INSTANCE_LINE = 14
local MSG_CELL_LINE_HEIGHT = 15
local MSG_CELL_LINE_LEADING = 3
local ROW_EDGE_INSET_SINGLE = 0
local ROW_EDGE_INSET_MULTI = 1
local ROW_INST_TOP_PAD = 3
local MSG_DISPLAY_MAX_CHARS = 50

local ACTION_BTN_LABEL_R, ACTION_BTN_LABEL_G, ACTION_BTN_LABEL_B = 1, 0.92, 0.22
local ACTION_BTN_LABEL_DISABLED_R, ACTION_BTN_LABEL_DISABLED_G, ACTION_BTN_LABEL_DISABLED_B = 0.48, 0.44, 0.32
local ACTION_BTN_INVITE_BG_R, ACTION_BTN_INVITE_BG_G, ACTION_BTN_INVITE_BG_B = 0.52, 0.12, 0.1
local ACTION_BTN_WHISPER_BG_R, ACTION_BTN_WHISPER_BG_G, ACTION_BTN_WHISPER_BG_B = 0.4, 0.16, 0.52
local ACTION_BTN_DISABLED_BG_R, ACTION_BTN_DISABLED_BG_G, ACTION_BTN_DISABLED_BG_B, ACTION_BTN_DISABLED_BG_A = 0.12, 0.12, 0.14, 0.72
local ACTION_BTN_BG_A = 0.96
local ACTION_BTN_HI_INVITE_R, ACTION_BTN_HI_INVITE_G, ACTION_BTN_HI_INVITE_B = 0.72, 0.26, 0.22
local ACTION_BTN_HI_WHISPER_R, ACTION_BTN_HI_WHISPER_G, ACTION_BTN_HI_WHISPER_B = 0.55, 0.26, 0.68
local ACTION_BTN_HI_A = 0.55
local ACTION_BTN_HEIGHT = 18

CEF.CONST = CEF.CONST or {}
do
  local CC = CEF.CONST
  CC.ROW_HEIGHT = ROW_HEIGHT
  CC.MAX_STORED = MAX_STORED
  CC.ENTRY_MAX_LISTING_AGE_SEC = ENTRY_MAX_LISTING_AGE_SEC
  CC.MAX_ROW_FRAMES_POOL = MAX_ROW_FRAMES_POOL
  CC.TABLE_PAD = TABLE_PAD
  CC.COL_GAP = COL_GAP
  CC.INSTANCE_LEVELS_TO_MSG_GAP = INSTANCE_LEVELS_TO_MSG_GAP
  CC.ROW_INSTANCE_LINE = ROW_INSTANCE_LINE
  CC.MSG_CELL_LINE_HEIGHT = MSG_CELL_LINE_HEIGHT
  CC.MSG_CELL_LINE_LEADING = MSG_CELL_LINE_LEADING
  CC.ROW_EDGE_INSET_SINGLE = ROW_EDGE_INSET_SINGLE
  CC.ROW_EDGE_INSET_MULTI = ROW_EDGE_INSET_MULTI
  CC.ROW_INST_TOP_PAD = ROW_INST_TOP_PAD
  CC.MSG_DISPLAY_MAX_CHARS = MSG_DISPLAY_MAX_CHARS

  CC.ACTION_BTN_HEIGHT = ACTION_BTN_HEIGHT
  CC.ACTION_BTN_INVITE_BG_R, CC.ACTION_BTN_INVITE_BG_G, CC.ACTION_BTN_INVITE_BG_B = ACTION_BTN_INVITE_BG_R, ACTION_BTN_INVITE_BG_G, ACTION_BTN_INVITE_BG_B
  CC.ACTION_BTN_WHISPER_BG_R, CC.ACTION_BTN_WHISPER_BG_G, CC.ACTION_BTN_WHISPER_BG_B = ACTION_BTN_WHISPER_BG_R, ACTION_BTN_WHISPER_BG_G, ACTION_BTN_WHISPER_BG_B
  CC.ACTION_BTN_DISABLED_BG_R, CC.ACTION_BTN_DISABLED_BG_G, CC.ACTION_BTN_DISABLED_BG_B, CC.ACTION_BTN_DISABLED_BG_A = ACTION_BTN_DISABLED_BG_R, ACTION_BTN_DISABLED_BG_G, ACTION_BTN_DISABLED_BG_B, ACTION_BTN_DISABLED_BG_A
  CC.ACTION_BTN_BG_A = ACTION_BTN_BG_A
  CC.ACTION_BTN_HI_INVITE_R, CC.ACTION_BTN_HI_INVITE_G, CC.ACTION_BTN_HI_INVITE_B = ACTION_BTN_HI_INVITE_R, ACTION_BTN_HI_INVITE_G, ACTION_BTN_HI_INVITE_B
  CC.ACTION_BTN_HI_WHISPER_R, CC.ACTION_BTN_HI_WHISPER_G, CC.ACTION_BTN_HI_WHISPER_B = ACTION_BTN_HI_WHISPER_R, ACTION_BTN_HI_WHISPER_G, ACTION_BTN_HI_WHISPER_B
  CC.ACTION_BTN_HI_A = ACTION_BTN_HI_A
  CC.ACTION_BTN_LABEL_R, CC.ACTION_BTN_LABEL_G, CC.ACTION_BTN_LABEL_B = ACTION_BTN_LABEL_R, ACTION_BTN_LABEL_G, ACTION_BTN_LABEL_B
  CC.ACTION_BTN_LABEL_DISABLED_R, CC.ACTION_BTN_LABEL_DISABLED_G, CC.ACTION_BTN_LABEL_DISABLED_B = ACTION_BTN_LABEL_DISABLED_R, ACTION_BTN_LABEL_DISABLED_G, ACTION_BTN_LABEL_DISABLED_B
end
